easy_admin:
    # On définit le nom de l'interface d'administration
    site_name: 'Gestion de Mangathèque'
    # On définit l'affichage de l'utilisateur
    user:
        display_name: true
        display_avatar: false
    design:
        # Ces lignes sont utiles pour CKEditor
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        # Ces lignes définiront notre menu
        menu:
            - { label: 'Serie' }
            - { entity: 'Serie', label: 'Serie', icon: 'book' }
            - { entity: 'Category', label: 'Catégories', icon: 'tag' }
            - { entity: 'Manga', label: 'Manga', icon: 'book-open' }
            - { label: 'Utilisateurs' }
            - { entity: 'User', label: 'Utilisateurs', icon: 'user' }
    formats:
        # Ici on définit le format des dates
        datetime: 'd/m/Y à H:i'
    entities:
        Serie:
            # Correspond au fichier serie.php
            class: App\Entity\Serie
            # On définit ci-dessous le contenu de la liste qui affichera les series et les critères de tri
            list:
                fields:
                    - id
                    - title
                    # Le champ ci-dessous affichera l'image de la serie
                    - { property: 'featured_image', label: 'Image', type: 'image', base_path: '%app.path.featured_images%' }
                    - { property: 'create_at', label: 'Créer' }
                    # Les catégories et les mots-clé sont listés ci-dessous
                    - { property: 'category', label: 'Catégories', type: 'string'}

                sort: ['create_at', 'desc']
            # On définit ci-dessous le contenu du formulaire d'ajout ou modification de la serie
            form:
                fields:
                    - title
                    # Affichage de l'éditeur Wysiwyg
                    - { property: 'content', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}
                    # Affichage du champ d'ajout d'image
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - users
                    # Les catégories et mots-clés peuvent s'afficher avec une sélection multiple
                    - { property: 'category', label: 'Catégories', type: 'entity', type_options: { class: 'App\Entity\Category', multiple: false}}
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - title   
                    - series
                sort: ['title', 'asc']     
            form:
                fields:
                    - title   
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                fields:
                    - id
                    - email
                    - username
                    - { property: 'roles', label: 'Rôles', type: json_array}
            form:
                fields:
                    - email
                    - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN'}}}            
        Manga:
            class: App\Entity\Manga
            label: 'Manga'
            list:
                fields:
                    - id
                    - title
                    - { property: 'featured_image', label: 'Image', type: 'image', base_path: '%app.path.featured_images%' }
            form:
                fields:
                    - title
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - user



     